spring.application.name=orderflow

app.version=1.2

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/orderflow}
spring.datasource.username=${DB_USERNAME:orderflow}
spring.datasource.password=${DB_PASSWORD:orderflow123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=never
