apiVersion: v1
kind: Service
metadata:
  name: orderflow-api
  labels:
    app: orderflow-api

spec:
  selector:
    app: orderflow-api

  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

  type: NodePort